### PR TITLE
Create ci.yml

### PR DESCRIPTION
**Pull request by harrystead2**

### CODE REVIEW

**Review by kirbyAlasdairAnswer — COMMENTED** [review]
do we maybe want to give the file a more descriptive name?

**Comment by milkshakeuk** [comment]
> do we maybe want to give the file a more descriptive name?

I think ci is probably fine, short for continuous integration? unless you would prefer a more verbose filename?

**Comment by kirbyAlasdairAnswer** [comment]
>

**Review by kirbyAlasdairAnswer — APPROVED** [review]

**Review by SWhyteAnswer — APPROVED** [review]

**Review by milkshakeuk — CHANGES_REQUESTED** [review]
Can you rename the file `continuous-integration.yml` please.

**Review by milkshakeuk — APPROVED** [review]
Thanks!

**Pull request merged**
